addons:
  sonarqube: true
env:
	global:
		- secure: "WRPM+KCXefrLVlA8IunzDg4LLxhZ01Xy8kxU8NZEknFS6FOpGVG7BPoVDHu2h3BvegsLYdxHVZ5/WjQfDowr1ENpoghCojfQbV9K4vg7eJ3qfmTPzft3Ymx8+gAUyIiqjyFV/CineJ4hkdn+6NQ6GKCfjXQ8q0TZde836ZS8IfskJoNnB6UdqifPCQR/q6tLWdEhY8MmR+CgQTleXJItmk5FxHUhcJ92HiOjfvOQOaPWguBH+Zzo4epHWgTmzwljB1ZV4XOCoIeogFNmTD4g3TwH+mzGjWkOMR/LXqpbWyfu0uFvVRCv1gkEE+AWq8s+UoOTnqiTKWjfbvDMbFUh14ZL4txiNdkA3B9zRC5FGe0z3G/SCSmec59nSdCFpfTHxjxR4uLw+Osn0mhV3nPfgq8NuTBHKFJSpHaZWk2U7ib4Km5chrniAie/QOmCCscqM925WprdiHNzFd5vZR854ZvyGAzCXMH4urggGnqM90t7NgaRu6IRJZPBS1qF5GbDf6vIxEM4LyBRlgLDozxKlAEOcsbRe6lZz1zUB4NIO/G9N0aDcjtqoFstOC7eJAcTJCRJtlYDjCvjv4nq8xMiMguBEuSb6D2BnZL+KmdOjLZG/5B51Wep7nPkE26YbIRiNrQcpEJgArNy4uNoTnCkqXaf4yQCnFRnCepqv+qmAOM="
language: java
script:
- jdk_switcher use oraclejdk7
- gradle clean
- gradle build
- gradle test
- jdk_switcher use oraclejdk8
- gradle clean
- gradle build
- gradle test
- sonar-scanner -Dsonar.login=$SONAR_HO -Dsonar.projectKey=ZuInnoTe:hadoopoffice -Dsonar.projectName=HadoopOffice -Dsonar.sources=./fileformat/src
