addons:
  sonarqube: true
env:
	global:
		- secure: "AsirCyvgMujWSSlZdiyNAfwEBY1RQbgY5bwNWHDhHwnhfkFVOX/o5t3Ubkd9fVD7k5Fd2vgV5CwKkg4C7mDuW+ujemRQDbjH8MHp5HouRGAbLP9KELkYNgYS3J7Z8lGnIRiK5N7PJ25jaIkr6DnbglRLY2kerVNcxDXO3D9+KexziDEhrTgplvxRDvVgIXCUggV08fqc0YGU/xu12yaH6JDJTrrov7T43AYeXHaPrM60uVrfxmgTPE2yArtVDpvTaEBlx8mEkuMMJDbJuJcfcDkcJMlIqmoy967Crx7wXnmOtjTD/XgFZlSSyV6z0vZm2TAlprXlCB/2qWdn7CMeuPodnpRFrWL6rSwauwbB9liqx9UK2/OhelOHuQJanBnX8zAylR5nISTBlNS0IP55zhSKutaX3Mx2Nbq8ROZuvUSvSkExka9Pf6HOHEDGue59rYrrb7oK3Alik9ev6d6lbhyGzeOmnTP8LonbJTo9urlA9SUtjzvTIV3wovi2I0pqlG/zF7bXqMmYVK6VeKLLb4fYz2hklKpUpmKroNMj3oBhZWsh8PbxRlJMzqfX4UNX3Lo9V4XLgNez9DT3g5mRPZQ2HHvonzr1LVAlz2m6ghvnbyaSc3uITxjrRzf+Bn61IyoigtswzDLye4SqzOWLwKUU/VrUN4M3XuTuD1H4eGc="
language: java
script:
- jdk_switcher use oraclejdk7
- gradle clean
- gradle build
- gradle test
- jdk_switcher use oraclejdk8
- gradle clean
- gradle build
- gradle test
- sonar-scanner -Dsonar.login=$SONAR_HO -Dsonar.projectKey=ZuInnoTe:hadoopoffice -Dsonar.projectName=HadoopOffice -Dsonar.sources=./fileformat/src
