addons:
  sonarqube: true
env:
  global:
  - secure: S2lOIdC2ajVpFaES2DumMz0tVN8IxcJyvcZfJwcws3dFR5qw5rFvALAnoOKHfZFkQg2G+t0FaIC+K97PluO5g168v2M+lNtIDV+Ja9EgnjnLjXTvkos5VYCiISB5xZN8tIL6tALLNx0s6CILnwT6DURiuJGNiKklfLPgSFet4eInMQyQhVvL4mO5bJHvciaBhj7CHjljr/yofvPv5bJPsYW3oVCrgtiqZzENrJAzyozuxV+u3R4HFj1ycmeaV55moiXEkjyDbPbYSNT9+kMbucd3g0mESGzNBW/PHy+Os85BDnoogTcMu2zEv/+ewGVlATz59kSb3Ea049BxbkvALSt3hrcDKpRFB3r8WhxS47YOGkKzC3qsROJT+R8bv3ebomg+Jm+jVgPWnVnK+2yMC1J6RA457kY7muZF/JyTqdC5zjOCHJciXcHgD3gkJEra1YgaDI1YbzW8QuttS5ptCj/wIvGaUETiL1HUI52Dok/ziDW9cScLvrSL57DG70O4JXN9xcf6lrgO2LsX6wAn5lrNHzcAuX4XrzAcJFhURqb2dtwyNwSLIbO8Ex1+1dKQIc17xYPe+4HxKsczZVklj298plb0vCsZMEXuC13oNT1ODGtjJAGeSM620nskxkC9g+l5ktz9HduQE1o56ceKySWnyJeqHb1jIhXdmEx4jWs=
  - secure: CHLTy7YKb0Dgtyuud08VBQVpQ+HP+ofyZpTnUFiJYSx2bbplofG9hCGco4TCXR2fFaDWKJ6dguTszZHacLM6iLKI/nCtFG4WzwY4fjJybs+9skvlhc9PNzvDUJeHDrhvdPMyJMYyhonPrCUb3oXvZUypNFkpv2fFXxfbnQJJbFCa6zUOTh2ZhtRdwBJEEPnCoA3+1346T+llYgi7b71ApjrbLUFVVE1S//2vX3HLroGl2OgNJN5sVZzlpRn+BRaaAx8/DiutYbnmMXvllP7a5WOVdWiPA5COE7JKZkldaJPBbAfT+ApG/tCGgG313FQXG0xOgrQAr9qwwkx+5mbwC5XJmiDilI1+/l1+dxtSHTuLAzZxDf2jzcHoGS0e0Yr4wvcS73/JGTTjGGlTEmMOoXSIJAQzMbX9UxrnmnLqAgnw35pPAAPRTac5lt7unbjhsTtHpJ6Gs4mNX4XdWAluDBLp1tLCa4ngGm6GFHKsqtVaCjV0nSvBNdUczmtLcr6LuaL3tQVff6kJead88KQV0oDCFNVsnjDKIXX36PdPQSgg6RlgQVfPfvlhujvxMOItbgR+24oU56pnnNNjQUMPoKFvqow4FNtNZY3tFMUdPbAmcTVbX1Rn6ALR5hrM+admOi99huhPFKaJOPvBU79CubgUqdv1i+xk3/K2NDB/qDA=
language: java
script:
- jdk_switcher use oraclejdk7
- gradle clean
- gradle build
- gradle test
- jdk_switcher use oraclejdk8
- gradle clean
- gradle build
- gradle test
- sonar-scanner -Dsonar.login=$SONAR_HO
  
