addons:
  sonarqube: true
env:
  global:
  - secure: S2lOIdC2ajVpFaES2DumMz0tVN8IxcJyvcZfJwcws3dFR5qw5rFvALAnoOKHfZFkQg2G+t0FaIC+K97PluO5g168v2M+lNtIDV+Ja9EgnjnLjXTvkos5VYCiISB5xZN8tIL6tALLNx0s6CILnwT6DURiuJGNiKklfLPgSFet4eInMQyQhVvL4mO5bJHvciaBhj7CHjljr/yofvPv5bJPsYW3oVCrgtiqZzENrJAzyozuxV+u3R4HFj1ycmeaV55moiXEkjyDbPbYSNT9+kMbucd3g0mESGzNBW/PHy+Os85BDnoogTcMu2zEv/+ewGVlATz59kSb3Ea049BxbkvALSt3hrcDKpRFB3r8WhxS47YOGkKzC3qsROJT+R8bv3ebomg+Jm+jVgPWnVnK+2yMC1J6RA457kY7muZF/JyTqdC5zjOCHJciXcHgD3gkJEra1YgaDI1YbzW8QuttS5ptCj/wIvGaUETiL1HUI52Dok/ziDW9cScLvrSL57DG70O4JXN9xcf6lrgO2LsX6wAn5lrNHzcAuX4XrzAcJFhURqb2dtwyNwSLIbO8Ex1+1dKQIc17xYPe+4HxKsczZVklj298plb0vCsZMEXuC13oNT1ODGtjJAGeSM620nskxkC9g+l5ktz9HduQE1o56ceKySWnyJeqHb1jIhXdmEx4jWs=
  - secure: gPR/bNPIjWGjLXT6j0+xVR6wCljHI4majGrU0j5bs7YqbGYZ2Syy1F9sBl8s9bTg7MroB1KSGCmuXRObnHXIS3fA76nNcbEox5yVjuy5tkEHX8b+FDIeBZYjTjMu5XOf7KPCz8nzmPecgWeLZEXYuevdt2nMUQ+I/aJ+KA2uqGCNocPmvgtggdSeLmuvhGAeHg58X9SHM0lWzvLO5bVQLHEcbcWS8CCVn3+gnjs9ei2oVuyfaZDlphOzPd6NAumiverPyHnRgA6IsEJZLy9a4DXkEchDZh4tlC5RUv1Qk5PqcD7n+bXzKlXQNPuovde/nttvMpdK4CycW0dIz2n14T3Px+5PMATk/qGQmQF+PGccfxCh2rfal0B4BA248haLhmBAYzNf39GI8ddfry8gZ1mcjLyZ31UXQAqpGFYfy8+p1u5SZyUeVjugnRLaZAqH6TJlZNQJlJaxEm6ecg9SWHuAfmzNg24OE9SUenjgH+mmlH2Gg/D7FKgdplX7G2p+PFti4tUchccK52w0gYh0veud8ww556W8BWgdPq92VGLv63XZlIwXVrhUP6UaGolDBvYg+WgAS+zpBUdNMV4Ts/AO+iqeIk8nJJcG5SICUoTX+XHWqCj86/aSKcOCDT/KoZWxVO3z3WdTw4n8kunl8fGXa1QPre6yy6P47VcJmB8=
language: java
script:
- jdk_switcher use oraclejdk7
- gradle clean
- gradle build
- gradle test
- jdk_switcher use oraclejdk8
- gradle clean
- gradle build
- gradle test
- sonar-scanner -Dsonar.login=$SONAR_HO
after_success:
- scripts/publish-javadoc.sh
- scripts/publish-junitreport.sh
